function ajaxGet(url,containerid,containerHeight,loadingDivStyle){ajaxBusy=1;ajaxLoadingScreen(containerid,containerHeight,loadingDivStyle);var randomnumber=Math.floor(Math.random()*99999999)
if(url.indexOf("cachebust=no")>-1){}else if(url.indexOf("?")==-1){url=url+"?cachebuster="+randomnumber;}else{url=url+"&cachebuster="+randomnumber;}
ajaxInitialize(url,'get',null,containerid);}
function ajaxPost(formObj,url,containerid,containerHeight,loadingDivStyle){ajaxBusy=1;var query=ajaxBuildPostQuery(formObj);ajaxLoadingScreen(containerid,containerHeight,loadingDivStyle);ajaxInitialize(url,'post',query,containerid);}
function ajaxLoadingScreen(containerid,containerHeight,loadingDivStyle){if(typeof loadingDivStyle!="undefined"){if(typeof containerHeight=="undefined"){var loadstatustext="<div style=' "+loadingDivStyle+" '><img src='/images/navigation/loading.gif' /> Requesting content...</div>";}else if(containerHeight==0){var loadstatustext="<div style=' "+loadingDivStyle+" '><img src='/images/navigation/loading.gif' /></div>";}}else{if(typeof containerHeight=="undefined"){var loadstatustext="<div style='text-align:center; padding-top:50px; clear:both;'><img src='/images/navigation/loading.gif' style='background:white;' /> Requesting content...</div>";}else if(containerHeight==0){var loadstatustext="<div><img src='http://www.soundclick.com/images/navigation/loading.gif' style='background:white;' /> Requesting content...</div>";}else{var loadstatustext="<div style='height:"+containerHeight+"px; text-align:center; padding-top:50px; clear:both;'><img src='/images/navigation/loading.gif' style='background:white;' /> Requesting content...</div>";}}
document.getElementById(containerid).innerHTML=loadstatustext;}
function ajaxInitialize(url,method,query,containerid){var xmlHttp;try{xmlHttp=new XMLHttpRequest();if(xmlHttp.overrideMimeType){xmlHttp.overrideMimeType('text/html; charset=iso-8859-1');}}catch(e){try{xmlHttp=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{xmlHttp=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){return false;}}}
xmlHttp.onreadystatechange=function(){if(xmlHttp.readyState==4&&(xmlHttp.status==200||window.location.href.indexOf("http")==-1)){document.getElementById(containerid).innerHTML=xmlHttp.responseText;ajaxBusy=0;}}
if(method=='get'){xmlHttp.open("GET",url,true);xmlHttp.send(null);}else{xmlHttp.open("POST",url,true);xmlHttp.setRequestHeader("Content-Type","application/x-www-form-urlencoded");xmlHttp.send(query);}
return false;}
function ajaxBuildPostQuery(formObj){var formdata="";for(i=0;i<formObj.elements.length;i++)
{if(formObj.elements[i].type=="text"){formdata=formdata+formObj.elements[i].name+"="+escape(formObj.elements[i].value)+"&";}else if(formObj.elements[i].type=="textarea"){formdata=formdata+formObj.elements[i].name+"="+escape(formObj.elements[i].value)+"&";}else if(formObj.elements[i].type=="checkbox"){formdata=formdata+formObj.elements[i].name+"="+formObj.elements[i].checked+"&";}else if(formObj.elements[i].type=="radio"){if(formObj.elements[i].checked==true){formdata=formdata+formObj.elements[i].name+"="+formObj.elements[i].value+"&";}}else{formdata=formdata+formObj.elements[i].name+"="+escape(formObj.elements[i].value)+"&";}}
return formdata;}